# Generated by Django 3.2.8 on 2021-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
